steps:
  - name: '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/terraform'
    args:
      - init
  - name: '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/terraform'
    args:
      - apply
      - -auto-approve
substitutions:
  _REGION: asia-northeast1
  _PROJECT_ID: chibawest-gamecenter
  _REPOSITORY: app-cloudbuild-terraform-builder