steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '--tag=${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/terraform',
    '.'
    ]
- name: '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/terraform'
  args: ['version']
substitutions:
  _REGION: asia-northeast1
  _PROJECT_ID: chibawest-gamecenter
  _REPOSITORY: app-cloudbuild-terraform-builder
images: ['${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/terraform']